
; filename:   BatchModeExample.idl



; PlotWindow Dimensions : !P.Multi(0,x,y) ergibt x*y unterfenster
!P.Multi=[0,2,2]




; structures und sharedlib etc definieren
phainit

; Strahl-Structure Source4 initialisieren - alle werte =0
beam={source4}

; CalculationMode : phase-space-density
cmode=3 


; versch Dateinamen:
beamlinefile='SGM.IDL.PHASE'
; enthaelt folgende dateinamen als arbeitsnamen:
;phase.field.tmp-eyrec
;phase.field.tmp-eyimc
;phase.field.tmp-ezrec
;phase.field.tmp-ezimc
tmpfile='phase.field.tmp'

infile  ='gb_8000' ; -eyrec, etc wird intern angehaengt

outfile ='gb_8000_SGM.result'



; Copy input nach tmp dateien
PhaseCopyFieldFiles, infile, tmpfile

; oder erstelle eigenen input:
;  New Gaussian-Beam with 193x67 Points
;                  ( nz , zmin , zmax , ny , ymin , ymax , waist, dist , lambda)
beam=phaSrcWFGauss( 128,  -1  , 1    , 128 ,  0  ,   3  ,  0.2 ,  0   , 60    )
; plotting
phaIntensitysurface,beam,'Gauss'

; beam in phase eigene datei struktur speichern
SavePhaseResults,beam, tmpfile
; namen fuer routinen sind noch verhandelbar !


; Batchmode starten ...
PhaseBatchMode, beamlinefile , tmpfile, cmode


; Ergebnisse in IDL laden
LoadPhaseResults, beam, tmpfile


; plotting
phaIntensitysurface,beam,'Zwischen-Ergebnis vor FFT'

;phaRealsurface_Ez,beam,'Zwischen-Ergebnis vor FFT'
;phaRealsurface_Ey,beam,'Zwischen-Ergebnis vor FFT'



;  Now let the beam propagate through a rectangular-slit (64x4) in the center of the beamline 
;                    nz1 ,nz2 ,ny1 ,ny2
; phaModSizeCut, beam, 32 , 96 , 62 , 66

;  For further calculations, we add a rim of zeros, so that we obtain a 256x256-field (after the slit)
;                  new:  nz ,ny             
 phaModSizeAddZeros,beam,128,128
; plotting
phaIntensitysurface,beam,'Zwischen-Ergebnis nach AddZeros'

;  Propagate the field with the FFT-far-field-propagator
;                     distance/[mm]
 phaPropFFTfar, beam,  1000


; plotting
phaIntensitysurface,beam,'Zwischen-Ergebnis nach FFT'
 
 
 

; beam in phase eigene datei struktur speichern
SavePhaseResults,beam, tmpfile


; erneuter run, leider mit derselben geometrie, man koennte aber auch 
;   ein anderes beamlinefile angeben
PhaseBatchMode, beamlinefile , tmpfile, cmode


; Move tmp nach ergebnis dateien - tmp files sind jetzt geloescht !!!
;   falls erneuter phase run gewuenscht muss nochmal nach tmpfile kopiert werden !!!
PhaseMoveFieldFiles, tmpfile, outfile


; End-Ergebnisse in IDL laden
LoadPhaseResults, beam, outfile

; plotting
phaIntensitysurface,beam,'Ergebnis'









