;; -*-idlwave-*-
;  File      : /afs/psi.ch/user/f/flechsig/phase/src/phaseidl/crl.pro
;  Date      : <11 Jul 13 08:23:00 flechsig> 
;  Time-stamp: <2013-07-16 22:32:49 flechsig> 
;  Author    : Uwe Flechsig, uwe.flechsig&#64;psi.&#99;&#104;

;  $Source$ 
;  $Date$
;  $Revision$ 
;  $Author$ 


;; test routine for crl

;+ 
; NAME:
;   crl_test
;
;
; PURPOSE:
;   test script for crl 
;
;
; CATEGORY:
;   phase_calc
;
;
; CALLING SEQUENCE:
;
;
;
; INPUTS:
;   
;
;
; OPTIONAL INPUTS:
;
;
;
; KEYWORD PARAMETERS:
;
; OUTPUTS:
;
;
;
; OPTIONAL OUTPUTS:
;
;
;
; COMMON BLOCKS:
;
;
;
; SIDE EFFECTS:
;
;
;
; RESTRICTIONS:
;   material properties hard coded - only Be so far
;
;
; PROCEDURE:
;
;
;
; EXAMPLE:
;   @crl_test.idl
;
;
; MODIFICATION HISTORY:
;    11.7.13 UF
;-

fname='/afs/psi.ch/project/phase/data/EZRE_GB_5000.h5'

file_id     = H5F_OPEN(fname)

z_vec= read_hdf5_dataset(file_id, '/z_vec')
y_vec= read_hdf5_dataset(file_id, '/y_vec')
t_vec= read_hdf5_dataset(file_id, '/t_vec')
field= read_hdf5_dataset(file_id, '/e_field')
;dataset_id1 = H5D_OPEN(file_id, '/z_vec')
;dataset_id2 = H5D_OPEN(file_id, '/y_vec')
;dataset_id3 = H5D_OPEN(file_id, '/t_vec')
;dataset_id4 = H5D_OPEN(file_id, '/e_field')
;z_vec       = H5D_READ(dataset_id1)
;y_vec       = H5D_READ(dataset_id2)
;t_vec       = H5D_READ(dataset_id3)
;field       = H5D_READ(dataset_id4)

;h5d_close, dataset_id1
;h5d_close, dataset_id2
;h5d_close, dataset_id3
;h5d_close, dataset_id4



h5f_close, file_id

nz   = n_elements(z_vec)
ny   = n_elements(y_vec)
nt   = n_elements(t_vec)

field1= reform(field,nz,ny,4,nt)
field2= reform(field1[*,*,*,0],nz,ny,4)

yreal= reform(field2[*,*,0], nz, ny)
yimag= reform(field2[*,*,1], nz, ny) 
zreal= reform(field2[*,*,2], nz, ny)
zimag= reform(field2[*,*,3], nz, ny)
help,field,field1,field2,yreal

yamp  = sqrt(yreal^2+yimag^2)
yphase= atan(yimag,yreal)
zamp  = sqrt(zreal^2+zimag^2)
zphase= atan(zimag,zreal)

print, 'start'
window,1
mycontour,zamp, z_vec, y_vec, title='z_amplitude', xtitle='z (mm)', ytitle='y (mm)'

window,2
mycontour,zphase, z_vec, y_vec, title='z_phase', xtitle='z (mm)', ytitle='y (mm)'

zv= z_vec*1e-3
yv= y_vec*1e-3

print, 'call crl'
crl, z_vec=zv, y_vec=yv, areal=zreal, aimag=zimag, bamp=bamp, bphase=bphase, crlamp=crlamp, crlphase=crlphase, wavelength=2e-10, apfac=0.5

window,3
mycontour, bamp, z_vec, y_vec, title='bamp', xtitle='z (mm)', ytitle='y (mm)'

window,4
mycontour, crlamp, z_vec, y_vec, title='crlamp', xtitle='z (mm)', ytitle='y (mm)'

window,5
mycontour, bphase, z_vec, y_vec, title='bphase', xtitle='z (mm)', ytitle='y (mm)'

window,6
mycontour, crlphase, z_vec, y_vec, title='crlphase', xtitle='z (mm)', ytitle='y (mm)'

print, 'done crl_test'
