;; -*-idlwave-*-
;  File      : /afs/psi.ch/user/f/flechsig/phase/src/phaseidl/crl.pro
;  Date      : <11 Jul 13 08:23:00 flechsig> 
;  Time-stamp: <28 Aug 13 16:13:40 flechsig> 
;  Author    : Uwe Flechsig, uwe.flechsig&#64;psi.&#99;&#104;

;  $Source$ 
;  $Date$
;  $Revision$ 
;  $Author$ 

;; test routine for crl

;+ 
; NAME:
;   crl_focus_1A_11m8.idl
;
;
; PURPOSE:
;   plot beam size as function of distgance from CRL.  
;   determines smallest spot and the corresponding distance
;
; CATEGORY:
;   phase_calc
;
;
; CALLING SEQUENCE:
;
;
;
; INPUTS:
;   
;
;
; OPTIONAL INPUTS:
;
;
;
; KEYWORD PARAMETERS:
;
; OUTPUTS:
;
;
;
; OPTIONAL OUTPUTS:
;
;
;
; COMMON BLOCKS:
;
;
;
; SIDE EFFECTS:
;
;
;
; RESTRICTIONS:
;   material properties hard coded - only Be so far
;
; PROCEDURE:
;
;
;
; EXAMPLE:
;   @crl_focus_1A.idl
;
;
; MODIFICATION HISTORY:
;    11.7.2013 UF
;    22.8.2013 RF  renamed from crl_rolf.idl to  crl_focus_1A.idl
;
; cd /home/scratch/phase/src/idlphase 
;
;-------------------- R e a d  I n p u t   F i l e s ---------------------------
;--------- Get Screen size in pixel -----------
;
!P.POSITION=[0.1, 0.1, 0.9,0.9]

print, !P.CHARSIZE

device, Get_Screen_size=size
screenX=size[0]
ScreenY=size[1]
Wx=ScreenX/4
Wy=ScreenY/4


Nz         = 151
Nzero      = 301
Nzero      = 0
Ninter     = 0                ;; interpolation
wavelength = 1d-10
sourcedist = 0
waist      = 27.7d-6 
sizez      =0.0006

fname0     ='/afs/psi.ch/project/phase/data/SwissFEL.out.dfl.h5'
stat       = dblarr(7)

;
;h5_read, fname0, z_vec=z_vec, y_vec=y_vec, wavelength=wavelength, zcomp=zcomp
;
;     bamp   =abs(zcomp)
;     bphase=atan(zcomp,/phase)
;    emf_statistics, bamp, y_vec=y_vec, z_vec=z_vec
; 
;     window,1, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-wx,YPOS=screeny-1*wy 
;     mycontour, bamp  ,z_vec*1e3,y_vec*1e3, xtitle='z (mm) ', ytitle='y (mm)', title='Source (amp)  ',xrange=[-0.3,0.3] ,yrange=[-0.3,0.3];
;
;     window,2, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-2*wx,YPOS=screeny-1*wy 
;     mycontour, bphase,z_vec*1e3,y_vec*1e3, xtitle='z (mm) ', ytitle='y (mm)', title='Source (phase)',xrange=[-0.3,0.3] ,yrange=[-0.3,0.3]


;   gaussbeam, dist=sourcedist, Nz=Nz,sizez=sizez, z_vec=z_vec, y_vec=y_vec, bcomp=field , w0=waist ,  wavelength=wavelength

  h5_read, fname0, z_vec=z_vec, y_vec=y_vec, wavelength=wavelength, zcomp=field

wavelength=double(1.1e-10)


 resize, z_vec=z_vec, y_vec=y_vec,field=field, Nzero =Nzero, Ninter = Ninter

  bamp = abs(field)
  bamp = bamp/max(bamp)
;  fit  = gauss2dfit(bamp, stat, z_vec, y_vec) 

  title= 'Source '+  string(sourcedist,FORMAT="(f6.1)") + 'm size='+  string(stat(2)*1e6,FORMAT="(f6.1)")+ ' x ' +string(stat(3)*1e6,FORMAT="(f6.1)") + ' um^2'
  window,1, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-wx,YPOS=screeny-1*wy 
  mycontour, bamp,z_vec*1e3,y_vec*1e3, xtitle='z (mm)', ytitle='y (mm)', title=title


drift = 120
 
 propfourier , drift=drift, z_vec=z_vec, y_vec=y_vec, field=field, wavelength=wavelength

;  prophuygens, field=field, z_vec=z_vec, y_vec=y_vec, drift=drift, wavelength=wavelength, Nu=900, Nv=900, Npi=0, plot=0
;  propfresnel , drift=drift, z_vec=z_vec, y_vec=y_vec, field=field, wavelength=wavelength

  propphase = atan(field,/phase)
  propamp   = abs(field)  
  propamp   = propamp/max(propamp)

;  fit  = gauss2dfit(propamp, stat, z_vec, y_vec) 

 title = 'Prop. to ' +  string(drift,FORMAT="(f6.1)") + 'm size='+  string(stat(2)*1e6,FORMAT="(f6.1)")+ ' x ' +string(stat(3)*1e6,FORMAT="(f6.1)")+ ' um^2'
 window,3, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-wx,YPOS=screeny-2*wy 
 mycontour, propamp,z_vec*1e3,y_vec*1e3, xtitle='z (mm)', ytitle='y (mm)', title=title+ ' (amp)'

crl, z_vec=z_vec, y_vec=y_vec, radius=(223.3e-6/17) ,size=500e-6, field=field,  wavelength=wavelength

;      window,5, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-wx,YPOS=screeny-3*wy 
;      mycontour, crlamp,z_vec*1e3,y_vec*1e3, xtitle='z (mm) ', ytitle='y (mm)', title='CRL (amp)',xrange=[-0.3,0.3] ,yrange=[-0.3,0.3]
;     window,6, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-2*wx,YPOS=screeny-3*wy 
;     mycontour, crlphase,z_vec*1e3,y_vec*1e3, xtitle='z (mm) ', ytitle='y (mm)', title='CRL (phase)';;,xrange=[-0.3,0.3] ,yrange=[-0.3,0.3]


bamp     =0
crlamp   =0
crlphase =0
propamp  =0
propphase=0
drift = 2.6                                    ;; System variable !c contains subscript of minimum, see help for function MIN

;resize, z_vec=z_vec, y_vec=y_vec,field=field, Nzero =0, Ninter = 2

; propfourier , drift=drift, z_vec=z_vec, y_vec=y_vec, field=field, wavelength=wavelength
  propfresnel , drift=drift, z_vec=z_vec, y_vec=y_vec, field=field, wavelength=wavelength
 
 bamp=abs(field)& bamp=bamp/max(bamp)& bamp=bamp^2
 title = 'Spot at ' + string(drift,FORMAT="(f5.1)") + ' m'

 width=0.04
 window,7, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-wx,YPOS=screeny-4*wy 
 mycontour, bamp  ,z_vec*1e3,y_vec*1e3, xtitle='z (mm) ', ytitle='y (mm)', title= 'Intensity: '+title;;, xrange=[-width/2,width/2] ,yrange=[-width/2,width/2]

; fit= gauss2dfit(bamp, stat, z_vec, y_vec)
; title = 'Spot at ' + string(drift,FORMAT="(f5.1)") + ' m, size = '+ string(stat[2]*1e6,FORMAT="(f4.2)")+ ' um (rms)'
; bphase = atan(field,/PHASE)
; window,8, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-2*wx,YPOS=screeny-4*wy 
; mycontour, bphase,z_vec*1e3,y_vec*1e3, xtitle='z (mm) ', ytitle='y (mm)', title= title,xrange=[-0.01,0.01] ,yrange=[-0.01,0.01]







writefield, field=bamp, z_vec=z_vec, y_vec=y_vec, filename='spot_'+ string(drift,FORMAT="(f4.1)") + '.dat', zmin=-4e-6, zmax = 4e-6, ymin=-4e-6, ymax=4e-6



