; -*-idlwave-*-
;  File      : /afs/psi.ch/user/f/flechsig/phase/src/phaseidl/crl.pro
;  Date      : <11 Jul 13 08:23:00 flechsig> 
;  Time-stamp: <18 Jul 13 15:57:34 flechsig> 
;  Author    : Uwe Flechsig, uwe.flechsig&#64;psi.&#99;&#104;

;  $Source$ 
;  $Date$
;  $Revision$ 
;  $Author$ 


;; test routine for crl

;+ 
; NAME:
;   drift_crl_test
;
;
; PURPOSE:
;   test script for crl 
;
;
; CATEGORY:
;   phase_calc
;
;
; CALLING SEQUENCE:
;
;
;
; INPUTS:
;   
;
;
; OPTIONAL INPUTS:
;
;
;
; KEYWORD PARAMETERS:
;
; OUTPUTS:
;
;
;
; OPTIONAL OUTPUTS:
;
;
;
; COMMON BLOCKS:
;
;
;
; SIDE EFFECTS:
;
;
;
; RESTRICTIONS:
;   material properties hard coded - only Be so far
;
;
; PROCEDURE:
;
;
;
; EXAMPLE:
;   @crl_test.idl
;
;
; MODIFICATION HISTORY:
;    11.7.13 UF
;-
fname='/afs/psi.ch/project/phase/data/aramis12_0.1nm_po_source_60m.h5'
fname='/afs/psi.ch/project/phase/data/SwissFEL.out.dfl.h5'
fname='/afs/psi.ch/project/phase/data/SwissFEL.out.dfl.phase_hdf5.h5'


h5_read, fname, zamp=zamp, zphase=zphase, z_vec=z_vec, y_vec=y_vec




print, 'start'
window,1
mycontour,zamp, z_vec, y_vec, title='z_amplitude', xtitle='z (mm)', ytitle='y (mm)'

window,2
mycontour,zphase, z_vec, y_vec, title='z_phase', xtitle='z (mm)', ytitle='y (mm)'

zv= z_vec*1e-3
yv= y_vec*1e-3

;print, 'call crl'
;crl, z_vec=zv, y_vec=yv, areal=zreal, aimag=zimag, bamp=bamp,
;bphase=bphase, crlamp=crlamp, crlphase=crlphase, wavelength=2e-10,
;apfac=0.5

print, 'call drift'
drift, z_vec=zv, y_vec=yv, areal=zreal, aimag=zimag, drift=123.,wavelength=1e-10, bcomp=bcomp, u=u1,v=v1,/plot
crl, z_vec=u1, y_vec=v1, acomp=bcomp, wavelength=1e-10, apfac=4.0, thickness=3e-5, radius=222.6e-6,bcomp=ccomp,bamp=damp
drift, z_vec=u1, y_vec=v1, acomp=ccomp, drift=3.,wavelength=1e-10, bamp=damp,u=u2,v=v2

window,3
mycontour, damp, u2*1e3, v2*1e3, title='bamp', xtitle='z (mm)', ytitle='y (mm)'

;window,4
;mycontour, crlamp, z_vec, y_vec, title='crlamp', xtitle='z (mm)', ytitle='y (mm)'

;window,5
;mycontour, bphase, z_vec, y_vec, title='bphase', xtitle='z (mm)', ytitle='y (mm)'

;window,6
;mycontour, crlphase, z_vec, y_vec, title='crlphase', xtitle='z (mm)', ytitle='y (mm)'

;print, 'done crl_test'
