; -*-idlwave-*-
;  File      : /afs/psi.ch/user/f/flechsig/phase/src/phaseidl/crl.pro
;  Date      : <11 Jul 13 08:23:00 flechsig> 
;  Time-stamp: <19 Jul 13 11:33:23 flechsig> 
;  Author    : Uwe Flechsig, uwe.flechsig&#64;psi.&#99;&#104;

;  $Source$ 
;  $Date$
;  $Revision$ 
;  $Author$ 


;; test the routines for wavefield propagation

;+ 
; NAME:
;   drift_test
;
;
; PURPOSE:
;   test script for crl 
;
;
; CATEGORY:
;   phase_calc
;
;
; CALLING SEQUENCE:
;
;
;
; INPUTS:
;   
;
;
; OPTIONAL INPUTS:
;
;
;
; KEYWORD PARAMETERS:
;
; OUTPUTS:
;
;
;
; OPTIONAL OUTPUTS:
;
;
;
; COMMON BLOCKS:
;
;
;
; SIDE EFFECTS:
;
;
;
; RESTRICTIONS:
;   material properties hard coded - only Be so far
;
;
; PROCEDURE:
;
;
;
; EXAMPLE:
;   @crl_test.idl
;
;
; MODIFICATION HISTORY:
;    11.7.13 UF
;-
; comments.
;   21.7.2013
;    - gauss2dfit does not converge
;    fname0: FWHM z = 20 um, y = 24 um
;    fname1:          80 um      84 um
;    fname :          28.2       37.6 um
;

;--------- Get Screen size in pixel -----------
device, Get_Screen_size=size
screenX=size[0]
ScreenY=size[1]
Wx=ScreenX/4
Wy=ScreenY/4

fname1='/afs/psi.ch/project/phase/data/aramis12_0.1nm_po_source_60m.h5'
fname0='/afs/psi.ch/project/phase/data/SwissFEL.out.dfl.h5'
fname ='/afs/psi.ch/project/phase/data/SwissFEL.out.dfl.phase_hdf5.h5'

;window,0, RETAIN=2
;print, ' '
;print, 'plot original file'
;h5_plot, fname0

;window,1, RETAIN=2
;print, ' '
;print, 'plot propagation with phase to 60 m'
;h5_plot, fname1

;window,2, RETAIN=2
;print, ' '
;print, 'plot drift to 60 m'
;print, 'start'


print, '---------------------Quellfile ---------------------------------'

;gaussbeam, dist=0, Nz=151,sizez=0.0006, z_vec=z_vec, y_vec=y_vec, bcomp=Quelle , w0=27.7e-6 , wavelength=wavelength
h5_read, fname0, z_vec=z_vec, y_vec=y_vec, wavelength=wavelength, zcomp=Quelle
bamp   =abs(Quelle)
bphase=atan(Quelle,/phase)

window,1, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-wx,YPOS=screeny-1*wy 
mycontour, bamp,z_vec*1e3,y_vec*1e3, xtitle='z (mm) ', ytitle='y (mm)', title='Source file  (amp)',xrange=[-0.3,0.3] ,yrange=[-0.3,0.3] 


;window,2, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-2*wx,YPOS=screeny-1*wy 
;mycontour, bphase,z_vec*1e3,y_vec*1e3, xtitle='z (mm) ', ytitle='y (mm)', title='Source file  (phase)',xrange=[-0.3,0.3] ,yrange=[-0.3,0.3]


s=total(bamp,1)
s=s/max(s)
;print, '---
- -Amplitude  ---'
;emf_statistics, bamp, z_vec=z_vec, y_vec=y_vec            
;print, '---- Intensity ---'
;intensity=bamp^2
;emf_statistics, intensity, z_vec=z_vec, y_vec=y_vec       


print, '------------- Propagated with PHASE ------------------------------'
h5_read, fname1, z_vec=z_vec, y_vec=y_vec, wavelength=wavelength, zcomp=zcomp
F1=abs(zcomp)
F2=atan(zcomp,/phase)
emf_statistics, F1, z_vec=z_vec, y_vec=y_vec                

window,3, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-wx, YPOS=screeny-2*wy
mycontour,F1,z_vec*1e3,y_vec*1e3, xtitle='z (mm) ', ytitle='y (mm)', title='Phase (amp)'

window,4, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-2*wx, YPOS=screeny-2*wy
mycontour,F2,z_vec*1e3,y_vec*1e3, xtitle='z (mm) ', ytitle='y (mm)', title='Phase (phase)'

;  1dim-projection 
f=total(F1,1)
f=f/max(f)

print, '---- Intensity ---'
intensity=F1^2
emf_statistics, intensity, z_vec=z_vec, y_vec=y_vec        ;; 

drift=60.0



print, '------------- Propagated with Fourier  -----------------------'

;h5_read, fname0, z_vec=z_vec, y_vec=y_vec, wavelength=wavelength, zcomp=Quelle

driftnear , drift=drift, z_vec=z_vec, y_vec=y_vec, acomp=Quelle, wavelength=wavelength, bcomp=bcomp, bamp=bamp, bphase=bphase

print, '---- -Amplitude  ---'
emf_statistics, bamp, z_vec=z_vec, y_vec=y_vec             

print, '---- Intensity ---'
intensity=bamp^2
emf_statistics, intensity, z_vec=z_vec, y_vec=y_vec       


window,5, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-wx,YPOS=screeny-3*wy 
mycontour, bamp,z_vec*1e3,y_vec*1e3, xtitle='z (mm) ', ytitle='y (mm)', title='Fourier propagation (amp)';;,xrange=[-0.3,0.3] ,yrange=[-0.3,0.3] 


;window,6, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-2*wx,YPOS=screeny-3*wy 
;mycontour, bphase,z_vec*1e3,y_vec*1e3, xtitle='z (mm) ', ytitle='y (mm)', title='Fourier propagation (phase)';;,xrange=[-0.3,0.3] ,yrange=[-0.3,0.3]

; 1dim-projection 
g=total(bamp,1)
g=g/max(g)

 a= n_elements(z_vec)

print,a
print,z_vec


print, '------------- Propagated with Fresnel  -----------------------'

h5_read, fname0, z_vec=z_vec, y_vec=y_vec, wavelength=wavelength, zcomp=zcomp

driftfresnel     , drift=drift, z_vec=z_vec, y_vec=y_vec, acomp=zcomp, wavelength=wavelength, bcomp=bcomp, bamp=bamp, bphase=bphase, u=u1, v=v1

window,7, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-wx,YPOS=screeny-4*wy 
mycontour, bamp,u1*1e3,v1*1e3, xtitle='z (mm) ', ytitle='y (mm)', title='Fresnel approx. (amp)',xrange=[-0.3,0.3] ,yrange=[-0.3,0.3] 


window,8, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-2*wx,YPOS=screeny-4*wy 
mycontour, bphase,u1*1e3,v1*1e3, xtitle='z (mm) ', ytitle='y (mm)', title='Fresnel approx. (phase)',xrange=[-0.3,0.3] ,yrange=[-0.3,0.3]

print, '---- -Amplitude  ---'
emf_statistics, bamp, z_vec=u1, y_vec=v1             

print, '---- Intensity ---'
intensity=bamp^2
emf_statistics, intensity, z_vec=u1, y_vec=v1    


;  1dim-projection 
h=total(bamp,1)
h=h/max(h)


;h5_write_genesis,'drift_out.h5', comp=zcomp, wavelength=wavelength, z_vec=z_vec, y_vec=y_vec 





window,10, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-3*wx, YPOS=0
plot, z_vec, f,YRANGE=[0,1], xtitle='width (mm) ', ytitle='Norm. Amplitude'
oplot, z_vec, g, color=3
oplot, u1 , h, color=2
oplot, z_vec, s, color=4


