;; -*-idlwave-*-
;  File      : /afs/psi.ch/user/f/flechsig/phase/src/phaseidl/crl.pro
;  Date      : <11 Jul 13 08:23:00 flechsig> 
;  Time-stamp: <2013-07-16 22:44:35 flechsig> 
;  Author    : Uwe Flechsig, uwe.flechsig&#64;psi.&#99;&#104;

;  $Source$ 
;  $Date$
;  $Revision$ 
;  $Author$ 
; 
; NAME:
;   poisson_spot_1A.idl
;
;
; PURPOSE:
;   calculates poisson spot for radiation of 1 Angstroem
;
;
;
; CATEGORY:
;
;
; CALLING SEQUENCE:
;
;
;
; INPUTS:
;   
;
;
; OPTIONAL INPUTS:
;
;
;
; KEYWORD PARAMETERS:
;
; OUTPUTS:
;
;
;
; OPTIONAL OUTPUTS:
;
;
;
; COMMON BLOCKS:
;
;
;
; SIDE EFFECTS:
;
;
;
; RESTRICTIONS:
;
;
; PROCEDURE:
;
;
;
; EXAMPLE:
;   @poisson_spot_1A.idl
;
;
; MODIFICATION HISTORY:
;    22.8.2013 RF
;
;
; cd /home/scratch/phase/src/idlphase 
;
;; Directory /home/scratch/phase/src/idlphase 
;
; Get Screen size in pixel -----------

!P.POSITION=[0.1, 0.1, 0.9,0.9]

print, !P.CHARSIZE

device, Get_Screen_size=size
screenX=size[0]
ScreenY=size[1]
Wx     =ScreenX/4
Wy     =ScreenY/4


Nz         = 1000
wavelength = 1d-10
sourcedist = 0
waist      = 27.7d-6 
sizez      = 0.001

drift = 1

Nu=300
Nv=Nu

gaussbeam, dist=sourcedist, Nz=Nz,sizez=sizez, z_vec=z_vec, y_vec=y_vec, bcomp=field, w0=waist ,  wavelength=wavelength

 Qamp   = abs(field)
 title = ' Source  with waist ' + string(waist*1e3) +  ' mm'
 window,1, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-1*wx,YPOS=screeny-1*wy 
   mycontour, Qamp,z_vec*1e3,y_vec*1e3, xtitle='z (mm)', ytitle='y (mm)', title=title+ ' (amp)'

 aperture , field=field, z_vec=z_vec, y_vec=y_vec, type = 20, P1 = -1e-5, P2=0;;, plot = 0, N=Nz, size=sizez 

     ap = abs(field)
     window,2, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-1*wx,YPOS=screeny-2*wy 
     mycontour, ap,z_vec*1e3,y_vec*1e3, xtitle='z (mm) ', ytitle='y (mm)', title='after aperture',xrange=[-0.1,0.1] ,yrange=[-0.1,0.1]


;prophuygens, field=field, z_vec=z_vec, y_vec=y_vec, drift=drift, wavelength=wavelength, Nu=Nu, Nv=Nv, Npi=1, plot=0

 propfourier , drift=drift, z_vec=z_vec, y_vec=y_vec, field=field, wavelength=wavelength

    propamp   = abs(field)
    propphase = atan(field,/phase)
    title = 'Propagated to ' +  string(drift,FORMAT="(f6.1)") + 'm'

    window,3, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-1*wx,YPOS=screeny-3*wy 
    mycontour, propamp,z_vec*1e3,y_vec*1e3, xtitle='z (mm)', ytitle='y (mm)', title=title+ ' (amp)',xrange=[-0.1,0.1] ,yrange=[-0.1,0.1]

    window,5, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-1*wx,YPOS=screeny-4*wy 
    dum  = size(ap) & sizea= dum[2]
    plot, z_vec*1e3 ,ap[*,sizea/2],xrange=[-0.1,0.1]
    dum  = size(propamp) & sizek= dum[2]
    oplot, z_vec*1e3 ,propamp[*,sizek/2] ,color=2


