;; -*-idlwave-*-
;  File      : /afs/psi.ch/user/f/flechsig/phase/src/phaseidl/crl.pro
;  Date      : <11 Jul 13 08:23:00 flechsig> 
;  Time-stamp: <31 Oct 14 10:28:28 flechsig> 
;  Author    : Uwe Flechsig, uwe.flechsig&#64;psi.&#99;&#104;

;  $Source$ 
;  $Date$
;  $Revision$ 
;  $Author$ 


;; test routine for fzp

;+ 
; NAME:
;   fzp_test
;
;
; PURPOSE:
;   test script for fzp 
;
;
; CATEGORY:
;   phase_calc
;
;
; CALLING SEQUENCE:
;
;
;
; INPUTS:
;   
;
;
; OPTIONAL INPUTS:
;
;
;
; KEYWORD PARAMETERS:
;
; OUTPUTS:
;
;
;
; OPTIONAL OUTPUTS:
;
;
;
; COMMON BLOCKS:
;
;
;
; SIDE EFFECTS:
;
;
;
; RESTRICTIONS:
;
; PROCEDURE:
;
;
;
; EXAMPLE:
;   @fzp_test.idl
;
;
; MODIFICATION HISTORY:
;    11.7.13 UF
;-
;
; cd /home/scratch/phase/src/idlphase 
;

print, 'charsize: ', !P.CHARSIZE
!P.CHARSIZE= 0.6
print, 'charsize: ', !P.CHARSIZE


Nz         = 501
wavelength = 3e-9
sourcedist = 1
waist      = 10e-6 
size       = 1e-3

emf=initphase()

;; source
emf->gaussbeam, dist=sourcedist, sizez=size, w0=waist,  wavelength=wavelength, nz=nz
title = 'source in ' +  string(sourcedist, FORMAT="(f6.1)") + 'm'

mywindow,2,1
emf->plotintensity, title=title+ ' (intensity)',charsize=!P.CHARSIZE
mywindow,2,2
emf->plotphase, /phunwrap, title=title+ ' (phase /phunw)',charsize=!P.CHARSIZE
;;emf->statistics


;; fzp
f= 0.5
d= 5e-4
emf->fzp, f=f, d=d
title = 'after FZP' 
mywindow,3,1
emf->plotintensity, title=title+ ' (intensity)',charsize=!P.CHARSIZE
mywindow,3,2
;;emf->plotphase, /phunwrap, title=title+ ' (phase /phunw)'
;;emf->plotphase, title=title+ ' (phase)',charsize=!P.CHARSIZE;

;; drift
drift = f/4
emf->propagate, drift=drift
title = 'Propagated to ' +  string(drift,FORMAT="(f6.1)") + 'm'
mywindow,4,1
emf->plotintensity, title=title+ ' (intensity)',charsize=!P.CHARSIZE
mywindow,4,2
emf->plotphase, title=title+ ' (phase /phunw)',charsize=!P.CHARSIZE
