; Compiles all of the *.pro files included into the phase4idl project at the moment


@phase4idl.compile_all.idl


;;;; INITIALY RUN AN EXAMPLE
wblf

;;; wait for key pressed
WaitForEnter


;;; exit idl and return to shell
exit







