;; -*-idlwave-*-
;  File      : /afs/psi.ch/user/f/flechsig/phase/src/phaseidl/crl.pro
;  Date      : <11 Jul 13 08:23:00 flechsig> 
;  Time-stamp: <29 Aug 13 15:55:02 flechsig> 
;  Author    : Uwe Flechsig, uwe.flechsig&#64;psi.&#99;&#104;

;  $Source$ 
;  $Date$
;  $Revision$ 
;  $Author$ 

;; test routine for crl

;+ 
; NAME:
;   crl_focus_1A.idl
;
;
; PURPOSE:
;   plot beam size as function of distgance from CRL.  
;   determines smallest spot and the corresponding distance
;
; CATEGORY:
;   phase_calc
;
;
; CALLING SEQUENCE:
;
;
;
; INPUTS:
;   
;
;
; OPTIONAL INPUTS:
;
;
;
; KEYWORD PARAMETERS:
;
; OUTPUTS:
;
;
;
; OPTIONAL OUTPUTS:
;
;
;
; COMMON BLOCKS:
;
;
;
; SIDE EFFECTS:
;
;
;
; RESTRICTIONS:
;   material properties hard coded - only Be so far
;
; PROCEDURE:
;
;
;
; EXAMPLE:
;   @crl_focus_1A.idl
;
;
; MODIFICATION HISTORY:
;    11.7.2013 UF
;    22.8.2013 RF  renamed from crl_rolf.idl to  crl_focus_1A.idl
;
; cd /home/scratch/phase/src/idlphase 
;
;-------------------- R e a d  I n p u t   F i l e s ---------------------------
;--------- Get Screen size in pixel -----------
;
!P.POSITION=[0.1, 0.1, 0.9,0.9]

print, !P.CHARSIZE

device, Get_Screen_size=size
screenX=size[0]
ScreenY=size[1]
Wx=ScreenX/4
Wy=ScreenY/4

Nzero      = 0
Ninter     = 0                ;; interpolation


 Nz         = 151
 wavelength = double(1d-10)
 sourcedist = 0
 drift      = 120.
 focusdist  = 11.715
 nimages    = 11          ;; number of foci to try around focusdist +/- 0.5 depth
 depth      = 1.          ;; depth for focus search


 waist      = double(27.7e-6) 
 crldist   = double(120.0)
 focusdist = double(2.5)
 depth     = double(0.5)

fname0     ='/afs/psi.ch/project/phase/data/SwissFEL.out.dfl.h5'
fname0     ='/afs/psi.ch/project/phase/data/SwissFEL_3keV.out.dfl.h5'
fname0     ='/afs/psi.ch/project/phase/data/SwissFEL_3keV.out.dfl.harm3.h5'
stat       = dblarr(7)


h5_read, fname0, z_vec=z_vec, y_vec=y_vec, wavelength=wavelength, zcomp=field

 bamp = abs(field)
 width=0.2
 window,1, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-wx,YPOS=screeny-1*wy 
 mycontour, bamp  ,z_vec*1e3,y_vec*1e3, xtitle='z (mm) ', ytitle='y (mm)', title= 'Amp Source', xrange=[-width/2,width/2] ,yrange=[-width/2,width/2]

 z=z_vec & y = y_vec & f = field

drift = 60 

propfourier , drift=drift, z_vec=z_vec, y_vec=y_vec, field=field, wavelength=wavelength
bamp=abs(field)& bamp=bamp/max(bamp)& bamp=bamp^2
width=0.8
title = 'fourier ' + string(drift1,FORMAT="(f5.1)") + ' m, size = '+ string(stat[2]*1e6, FORMAT="(f4.2)")+ textoidl(' \mum (rms)')
window,6, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-2*wx,YPOS=screeny-4*wy 
mycontour, bamp  ,z_vec*1e3,y_vec*1e3, xtitle='z (mm) ', ytitle='y (mm)', xrange=[-width/2,width/2] ,yrange=[-width/2,width/2]

 z_vec =z &  y_vec = y &  field = f

propfresnel , drift=drift, z_vec=z_vec, y_vec=y_vec, field=field, wavelength=wavelength 

bamp=abs(field)& bamp=bamp/max(bamp)& bamp=bamp^2
width=0.8
title = 'fresnel ' + string(drift1,FORMAT="(f5.1)") + ' m, size = '+ string(stat[2]*1e6, FORMAT="(f4.2)")+ textoidl(' \mum (rms)')
window,7, RETAIN=2, XSIZE=wx, YSIZE=wy ,XPOS=screenx-wx,YPOS=screeny-4*wy 
mycontour, bamp  ,z_vec*1e3,y_vec*1e3, xtitle='z (mm) ', ytitle='y (mm)', xrange=[-width/2,width/2] ,yrange=[-width/2,width/2]
