; -*-idlwave-*-
;  File      : /afs/psi.ch/user/f/flechsig/phase/src/phaseidl/crl.pro
;  Date      : <11 Jul 13 08:23:00 flechsig> 
;  Time-stamp: <19 Jul 13 11:33:23 flechsig> 
;  Author    : Uwe Flechsig, uwe.flechsig&#64;psi.&#99;&#104;

;  $Source$ 
;  $Date$
;  $Revision$ 
;  $Author$ 


;; test routine for crl

;+ 
; NAME:
;   drift_test
;
;
; PURPOSE:
;   test script for crl 
;
;
; CATEGORY:
;   phase_calc
;
;
; CALLING SEQUENCE:
;
;
;
; INPUTS:
;   
;
;
; OPTIONAL INPUTS:
;
;
;
; KEYWORD PARAMETERS:
;
; OUTPUTS:
;
;
;
; OPTIONAL OUTPUTS:
;
;
;
; COMMON BLOCKS:
;
;
;
; SIDE EFFECTS:
;
;
;
; RESTRICTIONS:
;   material properties hard coded - only Be so far
;
;
; PROCEDURE:
;
;
;
; EXAMPLE:
;   @
;
;
; MODIFICATION HISTORY:
;-
; comments.

bamp =dindgen(Nz,Nz)

wavelength =1e-10
Nz         =201
sourcedist = 0
drift      = 60
sizez      = 0.0006
;
; Parameters for XFEL-beam 
;
gaussbeam, dist=sourcedist, Nz=Nz,sizez=sizez, z_vec=z_vec, y_vec=y_vec, bcomp=bcomp , w0=27.7e-6 , wavelength=wavelength
;slit,       bcomp=bcomp, sizez=0.0001,sizey= 0.0002, Nz=Nz, Ny=Ny, sizez=sizez, wavelength=wavelength, y_vec=y_vec, z_vec=z_vec

 title = string(sourcedist)
 title = 'gaussbeam at '+ title + ' m'

  window,0, RETAIN=2, XSIZE=500, YSIZE=400,XPOS=1400, YPOS=770
  bamp = abs(bcomp)
  mycontour, bamp,z_vec,y_vec, xtitle='z (mm)', ytitle='y (mm)', title=title
  if (sourcedist ne 0) then  window,1, RETAIN=2, XSIZE=500, YSIZE=400, XPOS=900, YPOS=770
  if (sourcedist ne 0) then  bphase = atan(bcomp,/phase)
  if (sourcedist ne 0) then  mycontour, bphase,z_vec,y_vec, xtitle='z (mm)', ytitle='y (mm)', title='gaussbeam (phase)'


  print, '------------- Amplitude -----------------'
  emf_statistics, bamp, y_vec=y_vec, z_vec=z_vec

  print, '------------- Intensity -----------------'
  Intensity = bamp^2
  emf_statistics, Intensity, y_vec=y_vec, z_vec=z_vec
  



 print, '------------- Propagated beam -----------------'

driftFourier , drift=drift, z_vec=z_vec, y_vec=y_vec, acomp=bcomp, wavelength=wavelength, bcomp=prop ;; , $
;            plot=0
           
 propamp   = abs(prop)
 propphase = atan(prop,/phase)

 title = 'propagate to '+ string(drift)+ ' m'

 window,2, RETAIN=2 , XSIZE=500, YSIZE=400,XPOS=1400, YPOS=330
 mycontour, propamp,z_vec,y_vec, xtitle='z (mm)', ytitle='y (mm)', title=title
 title = title + ' (phase)'

 window,3, RETAIN=2, XSIZE=500, YSIZE=400,XPOS=900, YPOS=330
 mycontour, propphase,z_vec,y_vec, xtitle='z (mm)', ytitle='y (mm)', title=title


  print, '------------- Amplitude -----------------'
  emf_statistics, propamp, y_vec=y_vec, z_vec=z_vec

  print, '------------- Intensity -----------------'
  Intensity = propamp^2
  emf_statistics, Intensity, y_vec=y_vec, z_vec=z_vec
  



;driftnear , drift=-1*drift , z_vec=z_vec, y_vec=y_vec, acomp=prop, wavelength=wavelength, bcomp=back
; backamp=abs(back)
; emf_statistics, backamp, y_vec=y_vec, z_vec=z_vec
; window,4, RETAIN=2 , XSIZE=500, YSIZE=400,XPOS=1400, YPOS=0
; mycontour, backamp,z_vec,y_vec, xtitle='z (mm)', ytitle='y (mm)', title='backpropagate (amp)'








print, '------------- Analytical gauss beam -----------------'
print,'------------------------------------------drift = ',drift

gaussbeam, dist=drift, Nz=Nz,sizez=0.0006, z_vec=z_vec, y_vec=y_vec, bcomp=bcomp , w0=27.7e-6 , wavelength=wavelength


 title = 'gaussbeam at '+ string(drift) + ' m'

 bamp = abs(bcomp)

window,6, RETAIN=2 , XSIZE=500, YSIZE=400,XPOS=1400, YPOS=0
mycontour, bamp,z_vec,y_vec, xtitle='z (mm)', ytitle='y (mm)', title=title
title = title + ' (phase)'

bphase =atan(bcomp,/phase)
 window,7, RETAIN=2, XSIZE=500, YSIZE=400,XPOS=900, YPOS=0
 mycontour, bphase,z_vec,y_vec, xtitle='z (mm)', ytitle='y (mm)', title=title
 
 
 
 print, '------------- Amplitude -----------------'
  emf_statistics, bamp, y_vec=y_vec, z_vec=z_vec
 
 
 print, '------------- Intensity -----------------'
  Intensity = bamp^2
  emf_statistics, Intensity, y_vec=y_vec, z_vec=z_vec

;printf, '-------------- Projection of Intensity ------'

  vsum = total(Intensity,2)  
;  window,12,RETAIN=2,  XSIZE=600, YSIZE=400,XPOS=600, YPOS=800
;
;  plot, z_vec, vsum / max(vsum)
;  result=dindgen(6)
;  z=gaussfit(z_vec, vsum,result,NTERMS=5 )
;  print, ' rms = ',result[2]
;
;
;window,11,RETAIN=2,  XSIZE=600, YSIZE=400,XPOS=0, YPOS=800
; plot, z_vec,propamp[*,(Nz-1)/2], color = 2
 ;
;period = drift /sizez * wavelength
;print, ' Diffraction pattern with period ', period,' m (', period*1e6,' um)'
