;  File      : /afs/psi.ch/user/f/flechsig/phase/src/idlphase/updatehelp.idl
;  Date      : <25 Jan 08 13:47:57 flechsig> 
;  Time-stamp: <25 Jan 08 14:12:34 flechsig> 
;  Author    : Uwe Flechsig, uwe.flechsig&#64;psi.&#99;&#104;

;  $Source$ 
;  $Date$
;  $Revision$ 
;  $Author$ 

;; idl batch script called from the command line to update the
;; documentation in help.html

;; !the script should not be installed with phase !

updatehelp
exit
