#! /bin/sh
#   File      : /afs/psi.ch/user/f/flechsig/phase/src/bootstrap
#   Date      : <11 Dec 03 14:04:40 flechsig> 
#   Time-stamp: <21 Feb 06 14:31:51 flechsig> 
#   Author    : Uwe Flechsig, flechsig@psi.ch

#   $Source$ 
#   $Date$
#   $Revision$ 
#   $Author$ 

# the bootstrap script does a complete update of 
# autoconfig environment, i.e. one should run it 
# if configure.ac has been changed
# for minor changes (no new macros) running
# autoconf is sufficient

echo "==================================="
echo "  Bootstrap script for autoconfig  "
echo "  !!!  for developers only  !!!    "
echo "==================================="
echo "  before you use the script for the first time "
echo "  you have to run libtoolize [--force] "
echo "  to initialize your libtool environment "
echo " "
set -x
aclocal -I config
autoheader
automake --foreign --add-missing --copy
autoconf
# end /afs/psi.ch/user/f/flechsig/phase/src/bootstrap
