#! /bin/sh
#   File      : /afs/psi.ch/user/f/flechsig/phase/src/bootstrap
#   Date      : <11 Dec 03 14:04:40 flechsig> 
#   Time-stamp: <05 Feb 04 10:51:45 flechsig> 
#   Author    : Uwe Flechsig, flechsig@psi.ch

#   $Source$ 
#   $Date$
#   $Revision$ 
#   $Author$ 

echo "==================================="
echo "  Bootstrap script for autoconfig  "
echo "  for maintainers only             "
echo "==================================="
echo "  before you use the script for the first time "
echo "  you have to run libtoolize [--force] "
echo " "
set -x
aclocal -I config
autoheader
automake --foreign --add-missing --copy
autoconf



# end /afs/psi.ch/user/f/flechsig/phase/src/bootstrap
